### ISSUE TITLE
Failed to load config "prettier/vue" to extend from

### ISSUE THREAD

**Issue by yekver** [prettier/eslint-config-prettier#100]
```
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Failed to load config "prettier/vue" to extend from.
Referenced from: /usr/src/.eslintrc.json
    at PoolWorker.fromErrorObj (/usr/src/admin/node_modules/thread-loader/dist/WorkerPool.js:258:12)
    at configMissingError (/usr/src/admin/node_modules/eslint/lib/cli-engine/config-array-factory.js:233:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/usr/src/admin/node_modules/eslint/lib/cli-engine/config-array-factory.js:708:23)
    at ConfigArrayFactory._loadExtends (/usr/src/admin/node_modules/eslint/lib/cli-engine/config-array-factory.js:613:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/admin/node_modules/eslint/lib/cli-engine/config-array-factory.js:545:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/admin/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/admin/node_modules/eslint/lib/cli-engine/config-array-factory.js:545:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/admin/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
```

here is my `.eslintrc.json`:
```json
{
  "extends": [
    "eslint:recommended",
    "plugin:vue/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
    "prettier/vue"
  ],
  "plugins": ["prettier", "@typescript-eslint", "vue"],
  "env": {
    "node": true
  },
  "parser": "vue-eslint-parser",
  "parserOptions": {
     "parser": "@typescript-eslint/parser"
  },
  "rules": { ... }
}
```

**Comment by charlesscheuer** [comment]
what was the solution? just got the same error

**Comment by numfin** [comment]
Whats the solution? Me too!!!

**Comment by numfin** [comment]
without @vue/prettier everything works

**Comment by Zireael** [comment]
I'm getting same error

**Comment by danawoodman** [comment]
Getting the same here with:

```js
module.exports = {
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'prettier'],
  env: {
    browser: true,
    es6: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'prettier',
    'prettier/@typescript-eslint',
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  rules: {},
}

```

**Comment by lydell** [comment]
Feel free to create a reproduction repo and I could see if I can help figure out what's going on.

**Comment by nandorojo** [comment]
It would help to see your `package.json`, but doing this worked for me:

```
npm i eslint prettier-eslint eslint-config-prettier --save-dev
```

Then restarting VSCode.

**Comment by JackEdwardLyons** [comment]
Any news on this?

**Comment by monkpit** [comment]
@nandorojo I also needed to add `eslint-plugin-prettier` to this list and then it was working for me.

**Comment by nandorojo** [comment]
@monkpit Just edited my answer in case someone else faces the same issue.

**Comment by nafaabout** [comment]
I installed `@vue/eslint-config-prettier` and it solved it.

**Comment by ukaemma2** [comment]
this work for me guys `**@vue/eslint-config-prettier**`

**Comment by kenng** [comment]
if you are using current version `"eslint-config-prettier": "^8.0.0",` then it's no longer have to extends `prettier/vue`
check https://github.com/prettier/eslint-config-prettier, commit 03c79b9306892d4dbc828, it already merge vue.js to index.js.

Therefore, you just have to extends `prettier` or `eslint-config-prettier` in your `.eslintrc.js` and removed the `prettier/vue`.

**Comment by Anjinc188** [comment]
> I installed `@vue/eslint-config-prettier` and it solved it.

thank you

**Comment by bilal-288** [comment]
> 

Nice also worked for me
