### ISSUE TITLE
TypeError: prettier.getFileInfo.sync is not a function

### ISSUE THREAD

**Issue by ariesclark** [prettier/eslint-config-prettier#257]
Version 3 of Prettier breaks this plugin.

```
TypeError: prettier.getFileInfo.sync is not a function
Occurred while linting /.../src/components/inline-link.tsx:1
Rule: "prettier/prettier"
    at Program (/.../node_modules/.../eslint-plugin-prettier/eslint-plugin-prettier.js:143:70)
    at ruleErrorHandler (/.../node_modules/.../eslint/lib/linter/linter.js:1050:28)
    at /.../node_modules/.../eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
```

### In 3.0.0 release notes:

prettier.getFileInfo.sync is removed
See: https://prettier.io/blog/2023/07/05/3.0.0.html#api-1

**Comment by JounQin** [comment]
Duplicate with #255
